defaults:
  - _self_
  - environment: safety_grid

hydra:
  run:
    dir: ${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/${hydra.job.name}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
    chdir: true

log_dir: outputs

training:
  safe: True
  cost_limit: 0
  seed: 0
  time_limit: 100
  episodes_per_epoch: 100
  evaluation_episodes: 100
  epochs: 200
  eval_every: 5
  render_episodes: 1
  precision: 32
  parallel_envs: 20
  scale_reward: 1.

agent:
  replay_buffer:
    capacity: 1000
  batch_size: 32
  discount: 0.99
  actor:
  n_layers: 2
  hidden_size: 128
  initial_log_lagrangians: [0.]
  critic:
    n_layers: 2
    hidden_size: 128
  actor_optimizer:
    lr: 3e-4
    eps: 1e-5
    clip: 0.5
  critic_optimizer:
    lr: 3e-4
    eps: 1e-5
    clip: 0.5
  lagrangians_optimizer:
    lr: 3e-4
    eps: 1e-8
    clip: 1e6
